[WIP] feat: add css selector support
openwebf/webf pull request #11
Opened 2022-08-04 09:42 UTC by devjiangzhou

- [ ] selector & rule parser
- [ ] match rule for element
- [ ] match unit test
- [ ] update style
- [ ] inline style text
- [ ] optimize query selector

2022-08-04 10:02 UTC, andycall commented on webf/lib/src/css/element_rule_collector.dart
> + * Copyright (C) 2019-2022 The Kraken authors. All rights reserved.
There are no needs to carry Kraken copyright with new created files.

2022-08-29 16:57 UTC, XGHeaven commented on webf/lib/src/css/style_sheet.dart
> +  late List<CSSRule> _cssRules;
换成 final 把，把下面的 from 构造器改一下就好了。

`CSSStyleSheet.from(this.content, {this.disabled = false, this.href}): _cssRules = CSSParser(content).parseRules();`

2022-08-29 16:57 UTC, XGHeaven commented on webf/lib/src/css/values/color.dart
> +    final computedValue = variable?.computedValue('');
如果 variable !== null 的话，直接短路到 return 就好了吧。

2022-08-29 16:57 UTC, XGHeaven commented on webf/lib/src/css/variable.dart
> +  Map<String, dynamic>? _storage;
拆成两个 Map，一个存解析前的值，一个存解析后的值。这样类型也可以具化成 Map<String, String> 和 Map<String CSSVariable>。而且 dynamic 看起来有点头疼

2022-08-30 02:27 UTC, devjiangzhou commented on webf/lib/src/css/style_sheet.dart
> +  late List<CSSRule> _cssRules;
ok

2022-08-30 02:43 UTC, devjiangzhou commented on webf/lib/src/css/values/color.dart
> +    final computedValue = variable?.computedValue('');
是说 variable == null 吧？
!= null 是需要解析出来具体 num 的

2022-08-30 02:48 UTC, devjiangzhou commented on webf/lib/src/css/variable.dart
> +  Map<String, dynamic>? _storage;
这还真没法儿拆, 因为Variable 可能存在使用在前，声明在后的情况。 所以无法在存储时直接将 Variable 解析了
比如下面这个，我在set var时根本不知道后面有没有这个值。
{
color: var(--a);
--a: red
}
我只用在 get --a 时，才能从 storage 里取出 value。
ps: 这种x疼的设计，在 css parser 中  processDeclarations 方法也碰到了。
可以帮我也看一下，有没有更好的办法

2022-08-30 05:48 UTC, XGHeaven commented on webf/lib/src/css/values/color.dart
> +    final computedValue = variable?.computedValue('');
就是
```dart
if (variable !== null) {
  v = double.tryParse(variable.computedValue('');
  // here，不需要往后走了，直接去 return 那边判断大小就好了
}
```

2022-08-30 05:59 UTC, XGHeaven commented on webf/lib/src/css/variable.dart
> +  Map<String, dynamic>? _storage;
我看 setCSSVariable 的时候只是解析表达式而已，并不会涉及到实际的求值操作呀。感觉和声明先后没关系吧

2022-08-30 06:24 UTC, devjiangzhou commented on webf/lib/src/css/values/color.dart
> +    final computedValue = variable?.computedValue('');
👌

2022-08-30 07:13 UTC, devjiangzhou commented on webf/lib/src/css/variable.dart
> +  Map<String, dynamic>? _storage;
哦～，我还以为你说的解析是要求值，那我拆一下，这样子也会提供 check loop 效率

2022-08-31 17:10 UTC, XGHeaven commented on webf/lib/src/css/variable.dart
> +  bool _checkStorageLoop(String identifier) {
感觉有点粗暴，chrome 也是这么干的么？

2022-09-01 00:15 UTC, devjiangzhou commented on webf/lib/src/css/values/color.dart
> +    v = double.tryParse(computedValue);
我加个 spec

2022-09-01 00:18 UTC, devjiangzhou commented on webf/lib/src/css/style_declaration.dart
> +  void union(CSSStyleDeclaration declaration) {
union：不需要告诉外部有更新，就是将所有 properties 合并起来即可
diff: 需要告诉外部有更新，是因为diff 是在处理 union 后的properties 和 element 当前 style 的比对，而且map 结构不满足 important 的处理， inline 优先级和 important 优先级无法处理了。

2022-09-01 00:22 UTC, devjiangzhou commented on webf/lib/src/css/rule_set.dart
> + * Copyright (C) 2019-2022 The Kraken authors. All rights reserved.
done

2022-09-01 02:19 UTC, devjiangzhou commented on webf/lib/src/css/rule_set.dart
> +    void insertRule(String key, CSSRule rule, CSSMap map) {
放在这儿，是不想让这个类其他地方可以调用这个insert，

2022-09-01 02:57 UTC, XGHeaven commented on webf/lib/src/css/rule_set.dart
> +    void insertRule(String key, CSSRule rule, CSSMap map) {
那可以变成一个私有方法

2022-09-01 03:00 UTC, devjiangzhou commented on webf/lib/src/css/rule_set.dart
> +    void insertRule(String key, CSSRule rule, CSSMap map) {
私有方法也阻止不了这个类的其他内部方法调用 insert

2022-09-01 03:10 UTC, XGHeaven commented on webf/lib/src/css/style_declaration.dart
> +  void union(CSSStyleDeclaration declaration) {
1. 如果 union 是这个逻辑的话，为什么要循环两次，而且这两次都是取的 other._pendingProperties 的。感觉直接循环 other._pendingProperties 就可以了。
2. CSSStyleDeclaration 应该还需要有一个 _pendingImportants 吧，这样才能和 _pendingProperties 配对使用。不知道我理解是不是有什么偏差。
3. 从语义上定义，一个东西 diff 另一个东西，应该是不产生副作用的。就像是 git diff 总不会直接把本地文件改了吧。如果要实现你的这个效果，我觉得就不应该叫 diff 了，而是叫 update 更好一些。

2022-09-01 03:37 UTC, devjiangzhou commented on webf/lib/src/css/style_declaration.dart
> +  void union(CSSStyleDeclaration declaration) {
1. 循环两次： 第一次是针对 current declaration，用来更新 current declaration 第二次针对 other declaration，用来给 current declaration 添加新的property
   只取 pending properties 是因为被比对的 declaration 中只有 pending 有值, 且可以只考虑 pending 有值
2. _pendingImportants 是为了解决什么问题呢？
3. 改成 merge 吧，这样子好理解。

2022-09-01 03:43 UTC, devjiangzhou commented on webf/lib/src/css/variable.dart
> +  bool _checkStorageLoop(String identifier) {
没看 Chrome 相关逻辑，这个逻辑是在 wpt 测试时遇到的问题添加的

2022-09-01 04:43 UTC, XGHeaven commented on webf/lib/src/css/rule_set.dart
> +    void insertRule(String key, CSSRule rule, CSSMap map) {
哦哦，那也行吧。我主要是担心 dart 每次都会创建闭包，性能会差一些。

2022-09-01 05:32 UTC, XGHeaven commented on webf/lib/src/css/style_declaration.dart
> +  void union(CSSStyleDeclaration declaration) {
我对这块代码不是很熟，可能理解会有偏差，不对的话你就纠正下。

1. 在不考虑 important 的情况下，现在 union 的意思应该是，第一步把 current 上有且 other 的 pending 也有的赋值到 current 的 pending 上。第二步是把 other 有但是 current 没有的赋值到 current 的 pending 上。这两步是可以合并呀，就是把 other 的 pending 全部赋值到 current 的 pending 上。
2. 没关系，现在逻辑没问题的话就行。我后面再理解理解
3. 名字还是加个注释吧，就是区别下究竟在什么时候用哪个

2022-09-09 20:53 UTC, andycall commented on webf/lib/src/css/animation.dart
> +        print('123');
Remove log

2022-09-09 20:54 UTC, andycall commented on webf/lib/src/css/css_animation.dart
> +  String pseudoElement;
Should add toRaw() implements

2022-09-09 20:54 UTC, andycall commented on webf/lib/src/css/css_animation.dart
> +class AnimationEvent extends Event {
AnimationEvent class should appear in src/dom/event.dart

2022-09-09 20:56 UTC, andycall commented on webf/lib/src/css/css_animation.dart
> +
setter function should next to getter function

2022-09-09 21:11 UTC, andycall commented on webf/lib/src/css/css_animation.dart
> +          animation.oncancel = (AnimationPlaybackEvent event) {
Missing implementations

2022-09-09 21:12 UTC, andycall commented on webf/lib/src/css/css_animation.dart
> +        // for (var i = 0; i < keyframes.length; i++) {
Does these annotations still works?

2022-09-10 02:30 UTC, devjiangzhou commented on webf/lib/src/css/css_animation.dart
> +        // for (var i = 0; i < keyframes.length; i++) {
@youchant

2022-09-14 07:51 UTC, youchant commented on webf/lib/src/css/css_animation.dart
> +        // for (var i = 0; i < keyframes.length; i++) {
Unused code can be removed.

2022-09-17 15:28 UTC, devjiangzhou commented on webf/lib/src/css/style_declaration.dart
> +    _sheetStyle.forEach((property, value) {
只保留 _properties 即可。

2022-09-17 15:38 UTC, devjiangzhou commented
> 测试看到把 html 的从无后缀改成了数字后缀了，建议把 html 所有的测试截图都更新下吧
这个是用来处理一个 html 测试中需要进行多次 snapshot 才会走数字后缀逻辑，以前的无需重跑。

2022-09-18 06:56 UTC, XGHeaven commented
@devjiangzhou 测试的我想错了，没事了。

style 的例如这个 demo
```html
<head>
  <style>
    @keyframes A {}
    @keyframes B {}
  </style>
  <style>
    @keyframes C {}
  </style>
</head>
```

`A`/`B` 会生效，`C` 就不生效了，如果我把 `C` 放到第一个 style 里面，就又可以生效了。

2022-09-18 07:02 UTC, devjiangzhou commented
> @devjiangzhou 测试的我想错了，没事了。
> 
> style 的例如这个 demo
> 
> ```
> <head>
>   <style>
>     @keyframes A {}
>     @keyframes B {}
>   </style>
>   <style>
>     @keyframes C {}
>   </style>
> </head>
> ```
> 
> `A`/`B` 会生效，`C` 就不生效了，如果我把 `C` 放到第一个 style 里面，就又可以生效了。

应该不会， target.ownerDocument.ruleSet.keyframesRules， ruleset 会将所有的 style node content 都持有

2022-09-18 07:21 UTC, XGHeaven commented
@devjiangzhou 你可以试试这个 html，https://gist.githubusercontent.com/XGHeaven/f8bc6b6b1ae69fce747b1a2f656a3b92/raw/48f3f786e136644504a470c432ce7165c2f68c25/animation-diff-style.html 是有问题的。

另外我发现大小写有问题，`animation-name` 会自动取 lowerCase，导致都写 `A` 会出现找不到 keyframes 的情况。
https://gist.githubusercontent.com/XGHeaven/f8bc6b6b1ae69fce747b1a2f656a3b92/raw/156abea61cdeebcd9c2cec92edf1f83a3ced1a3f/animation-name-case.html

2022-09-18 10:31 UTC, devjiangzhou commented
> @devjiangzhou 你可以试试这个 html，https://gist.githubusercontent.com/XGHeaven/f8bc6b6b1ae69fce747b1a2f656a3b92/raw/48f3f786e136644504a470c432ce7165c2f68c25/animation-diff-style.html 是有问题的。
> 
> 另外我发现大小写有问题，`animation-name` 会自动取 lowerCase，导致都写 `A` 会出现找不到 keyframes 的情况。 https://gist.githubusercontent.com/XGHeaven/f8bc6b6b1ae69fce747b1a2f656a3b92/raw/156abea61cdeebcd9c2cec92edf1f83a3ced1a3f/animation-name-case.html

Fixed

2022-09-23 06:21 UTC, bainian commented
devtools似乎有问题不能展示了

2022-10-06 16:02 UTC, XGHeaven requested changes

2022-10-21 02:52 UTC, andycall approved these changes

2022-10-21 02:52 UTC, merged