Fix/multiple context crash
openwebf/webf pull request #118
Opened 2022-11-15 16:04 UTC by andycall

1. Fix the C++ bridge crash in two scenarios: 

+ The JSAtom can be shared between JSContexts, but we store the JSContext pointer at AtomicString class. That's a big mistake. If the previous stored JSContext are freeed, the bridge will crash if we copy previous JSContext allocated AtomicString to the current JSContext.
+ The InvokeModule API's callback could be called when the JSContext are already disposed in some special cases.

2. Add Multiple page integration test system.  Fixed #75

2022-11-16 06:19 UTC, XGHeaven requested changes

2022-11-18 04:46 UTC, andycall commented
@XGHeaven Please review again

2022-11-21 07:00 UTC, devjiangzhou approved these changes

2022-11-21 07:10 UTC, XGHeaven approved these changes

2022-11-21 08:26 UTC, merged