[WIP] perf: Improved element matching styles
openwebf/webf pull request #121
Opened 2022-11-16 15:41 UTC by devjiangzhou

- [ ]  Inherit style https://github.com/openwebf/webf/issues/108
- [ ]  ID / Name Map Cache

2022-11-22 01:28 UTC, andycall approved these changes

2022-11-22 06:39 UTC, suyulin commented
padding not support
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <style>
    body{
        margin: 0;
        padding: 0;
    }
    :root {
      --padding-var: 50px;
    }
    .my-div {
      padding: 0 var(--padding-var);
      background-color: black;
      width: 50px;
      height: 50px;
    }
  </style>
  <body>
    <div class="my-div"></div>
  </body>
</html>

```

2022-11-22 13:45 UTC, XGHeaven requested changes

2022-11-22 14:50 UTC, devjiangzhou commented on webf/lib/src/dom/document.dart
> +      return elements.last;
disconnectedCallback 已经处理了

2022-11-22 14:50 UTC, devjiangzhou commented on webf/lib/src/dom/document.dart
> +    return elementsByName[args.first];
同上

2022-11-22 14:56 UTC, devjiangzhou commented on webf/lib/src/css/style_sheet.dart
> -  // CSSStyleSheet(this.content, {this.disabled = false, this.href}) : cssRules = CSSParser(content).parseRules();
已经删除了

2022-11-22 15:28 UTC, devjiangzhou commented on webf/lib/src/css/css_property_name.dart
> +  WebkitAnimation,
删除了

2022-11-22 15:29 UTC, devjiangzhou commented on webf/lib/src/css/css_property_name.dart
> +enum CSSPropertyID {
等 CSS 这块儿参与的人多了再处理吧

2022-11-23 08:40 UTC, suyulin commented
css  transform: translate(-50%, -50%); not support
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .div {
            width: 500px;
            height: 500px;
            position: relative;
            background-color: #7F583F;
          }
          .span {
            background: orange;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
          }
    </style>
</head>
<body>
   <div class="div">
    <span class="span">居中</span>
   </div> 
</body>
</html>
```

2022-11-23 08:56 UTC, devjiangzhou commented
> css transform: translate(-50%, -50%); not support
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="UTF-8">
>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <title>Document</title>
>     <style>
>         .div {
>             width: 500px;
>             height: 500px;
>             position: relative;
>             background-color: #7F583F;
>           }
>           .span {
>             background: orange;
>             position: absolute;
>             top: 50%;
>             left: 50%;
>             transform: translate(-50%, -50%);
>           }
>     </style>
> </head>
> <body>
>    <div class="div">
>     <span class="span">居中</span>
>    </div> 
> </body>
> </html>
> ```

单独提 PR 修吧

2022-11-23 11:36 UTC, yifei8 commented
https://github.com/openwebf/webf/issues/142

2022-11-23 12:24 UTC, merged