fix: Overflow on the body can propagate to the viewport
openwebf/webf pull request #130
Opened 2022-11-20 15:23 UTC by LehemYang

#94 fix: Overflow on the body can propagate to the viewport

2022-11-21 06:50 UTC, andycall requested changes

2022-11-21 06:50 UTC, andycall commented on webf/lib/src/dom/element.dart
> +    if (tagName == BODY) {
Move these code to BodyElement

2022-11-21 06:50 UTC, andycall commented
@LehemYang Test specs also required.

2023-02-01 10:16 UTC, andycall approved these changes

2023-02-02 02:18 UTC, yifei8 approved these changes

2023-02-02 02:22 UTC, merged