[WIP]: refactor: redesign bridge code base
openwebf/webf pull request #18
Opened 2022-08-09 08:37 UTC by andycall

re-design the code base of bridge, fix hard-core problems and improve the performance.

The hard-core problems in bridge:

1. All implements are mixed with QuickJS API, memory management are messed, no one knows how many retaining bugs in there.
2. Al the binding glue code are written by hand, it wasted too much time.
3. The DOM tree are implemented by QuickJS data structures, it's not efficient. 

The new design:

1. [x] Split out the code base to `core` and `bindings` directory. core aims to DOM and Web API, bindings aims to all interactions to QuickJS API. 
2. [x] Manage QuickJS JSValue reference count with stack.
3. [x] Use code generator to generate all API glue code. 
6. [x] Make all initialize data to static and read-only.
7. [ ] re-design DOM API
    1. [x] EventTarget
    2. [x] Node
    3. [x] ContainerNode
    5. [x] Element
    8. [x] Document
    9. [x] Attr
    10. [x] CharacterData
    11. [x] DocumentFragment
    12. [x] Text
    13. [x] NodeList
    14. [x] CSSStyleDeclaration
    15. [ ] CustomElement
    16. [ ] CustomEvent
    17. [ ] DOM Selector
18. [x] Make more useful string statically and pre-allocated at build stage. 

Design Notes:

## Split out core and interface

<img width="300"  src="https://user-images.githubusercontent.com/4409743/158146252-27650e35-1a43-44f1-858a-886443ba8d62.png" />

## Type kind conversion with TypeScript and C++.

Based on the type define in TypeScript typings and generated the corresponding C++ call code. The call code are formed by C++ `Converter` class, responsible to easy convert any JS kind to C++ kind.

| JS                                             | C++                                        |
| ---------------------------------------------- | ------------------------------------------ |
| double                                         | TSDouble                                   |
| int64                                          | TSInt64                                    |
| boolean                                        | TSBool                                     |
| double?                                        | `TSOptional<TSDouble>`                |
| double \| null                                 | `TSNullable<TSDouble>`                       |
| double[]                                       | `TSSequence<TSDouble>`                       |
| type BlobPart = { name: string, value: double} | TSBlobPart // 自定义类型需要独立实现转换器 |
| any                                            | TSAny                                      |

Example:

```c++

template <>
struct Converter<TSDouble> : public ConverterBase<TSDouble> {
  static ImplType FromValue(JSContext* ctx, JSValue value) {
    assert(!JS_IsException(value));
    double v;
    JS_ToFloat64(ctx, &v, value);
    return v;
  }

  static JSValue ToValue(JSContext* ctx, double v) { return JS_NewFloat64(ctx, v); }
};
```

![image](https://user-images.githubusercontent.com/4409743/158155209-a378c705-78eb-4657-8edf-1170d98f34a4.png)

##  How properties and methods defined

JS code use prototype to access native defined properties and methods.

<img src="https://user-images.githubusercontent.com/4409743/158182308-11604243-afa4-4376-ab8e-075b9b5a793d.png" width="800" />

2022-09-22 17:04 UTC, andycall commented
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/4409743/191808276-2930d26c-7882-4586-aa1b-816dc674dcbe.png">

Append 10000 div elements
```javascript
let container = document.createElement('div');
for(let i = 0; i < 1000; i ++) {
    let child = document.createElement('div');
    for(let j = 0; j < 10; j ++) {
        let span = document.createElement('span');
        let text = document.createElement('helloworld');
        span.appendChild(text);
        child.appendChild(span);
    }
    container.appendChild(child);
}
```

**Before**: 50.7ms
**After**: 29.6 ms

2022-09-22 17:05 UTC, andycall commented
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/4409743/191808803-d4dc01cd-9099-4538-b623-14e96a82e011.png">

Insert 1000 DIV on the top.

```javascript
  let container = document.createElement('div');
  let child = document.createElement('div');
  let span = document.createElement('span');
  let text = document.createElement('helloworld');
  span.appendChild(text);
  container.appendChild(child);

  for (let i = 0; i < 1000; i ++) {
    let span = document.createElement('span');
    let text = document.createElement('helloworld');
    span.appendChild(text);
    child.insertBefore(span, child.firstChild);
  }
```

**Before**:  10.8ms
**After**: 2.62ms

2022-10-09 16:26 UTC, XGHeaven requested changes
- `bridge/third_party/quickjs/quickjs.c` file is empty, remove it.
- The integration snapshot files about `hsl`/`hsla` should not be added. Maybe rebase the main branch and rerun to fix it.

(PS: 实在是看不懂，只能 re 出一些无关紧要的东西了)

2022-10-09 16:26 UTC, XGHeaven commented on bridge/polyfill/src/index.ts
> +      value: value,
indent

2022-10-09 16:26 UTC, XGHeaven commented on bridge/polyfill/src/location.ts
> +import {URL} from './url';
code style: space around `URL`.

2022-10-09 16:26 UTC, XGHeaven commented on bridge/polyfill/src/location.ts
> +      return webfLocationReload.bind(this);
indent

2022-10-09 16:26 UTC, XGHeaven commented on integration_tests/scripts/core_integration_starter.js
> +    console.log(code);
Remove debug code

2022-10-10 03:02 UTC, andycall commented on bridge/CMakeLists.txt
> +#if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
My mistake

2022-10-21 02:09 UTC, devjiangzhou approved these changes

2022-10-21 02:52 UTC, merged