fix(flex): fix flex:1 failed when style minHeigh/minWidth
openwebf/webf pull request #28
Opened 2022-08-17 08:21 UTC by pba-cra

fix:https://github.com/openwebf/webf/issues/27

2022-08-17 14:35 UTC, andycall commented on webf/lib/src/rendering/flex.dart
> +            if(flexBasis == 0) {
code style.

2022-08-17 14:35 UTC, andycall commented on webf/lib/src/rendering/flex.dart
> +      if(layoutContentMainSize <= _getMinMainAxisSize(this)  && initialFreeSpace == 0) {
code style.

2022-08-17 14:36 UTC, andycall commented
test spec missing?

2022-08-21 15:11 UTC, andycall commented
Test spec required. @pba-cra

2022-08-21 15:11 UTC, andycall requested changes
Test spec required. @pba-cra

2022-08-21 15:59 UTC, andycall requested changes

2022-08-21 15:59 UTC, andycall commented on webf/lib/src/css/values/length.dart
> +    if (value == 0 && propertyName != FLEX_BASIS) {
CSSLengthValue should not depends on flex-basic property.

2022-08-23 13:27 UTC, devjiangzhou approved these changes

2022-08-23 13:58 UTC, andycall approved these changes

2022-08-23 13:58 UTC, merged