Fix/memory leaks
openwebf/webf pull request #487
Opened 2023-09-19 15:48 UTC by andycall

Fixed https://github.com/openwebf/webf/issues/482

Fixed the memory leaks caused by the UICommand::disposedBindingObject command not being executed. 

These memory leaks affected versions 0.14.1 to 0.15.0

2023-09-19 16:51 UTC, XGHeaven requested changes
And the better to change the title to a good one.

2023-09-19 16:51 UTC, XGHeaven commented on webf/lib/src/bridge/to_native.dart
> +      print('dispose $nativePtr');
remove print

2023-09-20 00:59 UTC, zjt123 commented
这个是否能弄个测试用例，便于自测及时发现问题

2023-09-22 12:07 UTC, XGHeaven approved these changes

2023-09-22 16:26 UTC, andycall commented
@zjt123 added

2023-09-25 03:34 UTC, zjt123 approved these changes

2023-09-25 08:09 UTC, merged